# Generated by Django 5.0 on 2026-03-03 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_went_well', models.TextField(blank=True)),
                ('what_was_challenging', models.TextField(blank=True)),
                ('needs_revisiting', models.TextField(blank=True)),
                ('do_differently', models.TextField(blank=True)),
                ('engagement_rating', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflections_created', to=settings.AUTH_USER_MODEL)),
                ('flagged_learners', models.ManyToManyField(blank=True, related_name='flagged_in_reflections', to=settings.AUTH_USER_MODEL)),
                ('lesson_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reflection', to='planning.lessonplan')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('content', 'Content'), ('admin', 'Admin'), ('learner', 'Learner'), ('resource', 'Resource'), ('communication', 'Communication')], max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('carried', 'Carried Over')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reflection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='reflections.lessonreflection')),
            ],
        ),
        migrations.CreateModel(
            name='CarryOverPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_items', models.JSONField(default=list)),
                ('reflection_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('partial', 'Partial')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carry_overs_to', to='planning.lessonplan')),
                ('origin_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_overs_from', to='planning.lessonplan')),
                ('open_tasks', models.ManyToManyField(blank=True, to='reflections.todotask')),
            ],
        ),
    ]
