# Generated by Django 5.0 on 2026-03-17 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_lessonreflection'),
        ('reflections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='reflection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='planning.lessonreflection'),
        ),
        migrations.DeleteModel(
            name='LessonReflection',
        ),
    ]
