# Generated by Django 5.0 on 2026-03-03 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('assessment_type', models.CharField(choices=[('test', 'Test'), ('assignment', 'Assignment'), ('exam', 'Exam'), ('practical', 'Practical'), ('oral', 'Oral'), ('project', 'Project')], max_length=20)),
                ('date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('total_marks', models.PositiveIntegerField()),
                ('term_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('term', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('moderated', 'Moderated')], default='draft', max_length=20)),
                ('requires_moderation', models.BooleanField(default=False)),
                ('moderation_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classrooms', models.ManyToManyField(related_name='assessments', to='schools.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_created', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.grade')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_assignments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.subject')),
                ('timetable_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.timetableslot')),
            ],
        ),
        migrations.CreateModel(
            name='ExamInvigilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilations', to='assessments.assessment')),
                ('chief_invigilator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_invigilations', to=settings.AUTH_USER_MODEL)),
                ('invigilators', models.ManyToManyField(blank=True, related_name='invigilations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.room')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_mark', models.DecimalField(decimal_places=2, max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('absent', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='assessments.assessment')),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_captured', to=settings.AUTH_USER_MODEL)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assessment', 'learner')},
            },
        ),
    ]
