# Generated by Django 5.0 on 2026-03-03 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('term', models.PositiveIntegerField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.subject')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('official', 'Official'), ('personal', 'Personal')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='draft', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('objectives', models.TextField()),
                ('activities', models.TextField()),
                ('differentiation', models.TextField(blank=True)),
                ('resources_note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_approved', to=settings.AUTH_USER_MODEL)),
                ('curriculum_outcomes', models.ManyToManyField(blank=True, to='planning.curriculumoutcome')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.lessonplan')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_submitted', to=settings.AUTH_USER_MODEL)),
                ('timetable_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='schools.timetableslot')),
            ],
        ),
        migrations.CreateModel(
            name='LessonDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial'), ('not_done', 'Not Done')], max_length=10)),
                ('coverage_percent', models.PositiveIntegerField(default=100)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_delivered', to=settings.AUTH_USER_MODEL)),
                ('lesson_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='planning.lessonplan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('returned', 'Returned'), ('rejected', 'Rejected')], max_length=15)),
                ('feedback', models.TextField(blank=True)),
                ('actioned_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='planning.lessonplan')),
            ],
        ),
    ]
