# Generated by Django 5.0 on 2026-03-17 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_lessonplanattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_went_well', models.TextField(blank=True, help_text='What aspects of the lesson were successful?')),
                ('challenges', models.TextField(blank=True, help_text='What challenges or difficulties were encountered?')),
                ('learner_engagement', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], default='good', max_length=20)),
                ('content_covered', models.PositiveIntegerField(default=100, help_text='Percentage of planned content covered (0-100)')),
                ('carry_over_needed', models.BooleanField(default=False, help_text='Should uncovered content be carried over to the next lesson?')),
                ('carry_over_notes', models.TextField(blank=True, help_text='What content needs to be carried over and why?')),
                ('adjustments_for_next_time', models.TextField(blank=True, help_text='What would you do differently next time?')),
                ('reflected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reflection', to='planning.lessonplan')),
                ('reflected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reflected_at'],
            },
        ),
    ]
