# Generated by Django 5.0 on 2026-03-12 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_classroom_homeroom_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday'), ('D1', 'Day 1'), ('D2', 'Day 2'), ('D3', 'Day 3'), ('D4', 'Day 4'), ('D5', 'Day 5'), ('D6', 'Day 6'), ('D7', 'Day 7'), ('D8', 'Day 8')], max_length=3),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday'), ('D1', 'Day 1'), ('D2', 'Day 2'), ('D3', 'Day 3'), ('D4', 'Day 4'), ('D5', 'Day 5'), ('D6', 'Day 6'), ('D7', 'Day 7'), ('D8', 'Day 8')], max_length=3),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('timetable', 'day', 'period', 'classroom')},
        ),
        migrations.CreateModel(
            name='TimetableConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_type', models.CharField(choices=[('week', 'Weekly (Mon-Fri)'), ('cycle', 'Cycle Days (Day 1-N)')], default='week', max_length=10)),
                ('num_days', models.PositiveIntegerField(default=5)),
                ('periods_per_day', models.PositiveIntegerField(default=7)),
                ('timetable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='schools.timetable')),
            ],
        ),
    ]
